import React, {useEffect, useMemo, useState} from 'react';
import MarketProfile from './MarketProfile.jsx';
import {ResponsiveContainer, ScatterChart, Scatter, XAxis, YAxis, Tooltip, CartesianGrid, ReferenceLine, Cell, LabelList} from 'recharts';
const pct=v=>v==null?'—':`${v>=0?'+':''}${v.toFixed(1)}%`;
const num=v=>v==null?'—':Math.round(v).toLocaleString();
const median=xs=>{const a=xs.filter(Number.isFinite).sort((a,b)=>a-b);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.floor(a.length/2)])/2:null;};
function Tip({active,payload}) {if(!active||!payload?.length)return null;const r=payload[0].payload;return <div className="lab-tooltip"><strong>{r.name}</strong><p>Permits / 1,000 homes: {r.permitsPer1000.toFixed(1)}</p><p>Asking rent growth: {pct(r.rentGrowth)}</p><p>5+ unit share of permits: {r.multiShare?.toFixed(0)}%</p><p>Click to inspect this metro</p></div>;}
export default function MetroComparison(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(()=>{try{return localStorage.getItem('ledger-selected-metro')||'12420';}catch{return '12420';}}),[sort,setSort]=useState('permitsPer1000'),[direction,setDirection]=useState(-1),[retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setError('');fetch('/api/re-metro-comparison',{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[retry]);
  const rows=useMemo(()=>data?[...data.rows].sort((a,b)=>{if(a[sort]==null)return 1;if(b[sort]==null)return -1;return direction*(typeof a[sort]==='string'?a[sort].localeCompare(b[sort]):a[sort]-b[sort]);}):[],[data,sort,direction]);
  const plotted=rows.filter(r=>r.permitsPer1000!=null&&r.rentGrowth!=null),mid=median(plotted.map(r=>r.permitsPer1000)),focus=rows.find(r=>r.code===selected)||rows[0];
  useEffect(()=>{try{localStorage.setItem('ledger-selected-metro',selected);}catch{}},[selected]);
  const order=k=>{setSort(k);setDirection(sort===k?-direction:-1);};
  if(error&&!data)return <div className="lab-empty" role="status"><h2>Metro comparison unavailable</h2><p>{error}</p><button className="lab-button" onClick={()=>setRetry(v=>v+1)}>Retry data</button></div>;
  if(!data)return <div className="lab-empty" role="status">Combining Census permit counts and housing stock with Zillow asking rents…</div>;
  return <>
    {data.partial&&<div className="lab-insight" role="status">Some sources are unavailable. Missing values remain blank; available data is shown with its observation dates.</div>}
    {data.stale&&<div className="lab-insight" role="status">{data.warning}</div>}
    <MarketProfile focus={focus} rows={rows} data={data} onSelect={setSelected}/>
    <div className="lab-section-top"><div><h2>Where can new supply challenge pricing power?</h2><p>Compare construction authorizations with asking-rent growth across {rows.length} metros.</p></div><span className="lab-tag">Observed data · {plotted.length}/{rows.length} paired</span></div>

    <section className="lab-panel"><div className="lab-section-top"><h2>Supply intensity × rent growth</h2><span className="lab-note">Each point is a metro · click to inspect</span></div>
      <div className="lab-chart" style={{height:380}}><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:24,right:32,left:8,bottom:32}}><CartesianGrid stroke="var(--border-subtle)"/><XAxis type="number" dataKey="permitsPer1000" name="Permits / 1,000 homes" stroke="var(--text-secondary)" label={{value:`${data.permitYear} permitted units per 1,000 existing homes`,position:'bottom',offset:10,fill:'var(--text-secondary)',fontSize:12}}/><YAxis type="number" dataKey="rentGrowth" name="Rent growth" unit="%" stroke="var(--text-secondary)" label={{value:'Asking rent · year over year',angle:-90,position:'insideLeft',fill:'var(--text-secondary)',fontSize:12}} domain={['auto','auto']}/><ReferenceLine y={0} stroke="var(--text-muted)"/><ReferenceLine x={mid} stroke="var(--chart-blue)" strokeDasharray="4 5"/><Tooltip content={<Tip/>}/><Scatter data={plotted} onClick={r=>setSelected(r.code)} cursor="pointer" isAnimationActive={false}>{plotted.map(r=><Cell key={r.code} fill={r.code===selected?'var(--chart-gold)':r.rentGrowth<0?'var(--chart-red)':'var(--chart-green)'} stroke={r.code===selected?'var(--text-primary)':'var(--page-bg)'} strokeWidth={r.code===selected?2:1}/>)}<LabelList dataKey="name" position="top" content={({x,y,index})=>plotted[index]?.code===selected?<text x={x} y={y-12} textAnchor="middle" fill="var(--text-primary)" fontSize={13}>{plotted[index].name}</text>:null}/></Scatter></ScatterChart></ResponsiveContainer></div>
      <p className="lab-note">Dashed line: median supply intensity in these {plotted.length} metros ({mid?.toFixed(1)}). Warm points: falling asking rents. Green points: flat or rising. Permits authorize future construction; they do not measure completions, construction underway, or net additions to stock.</p>
    </section>
    <section className="lab-panel"><h2>Compare the underlying numbers</h2><p className="lab-note">Click a column to sort or a metro to focus the chart.</p><div className="lab-table-wrap"><table className="lab-table"><thead><tr>{[['name','Metro'],['permitsPer1000','Permits / 1k'],['rentGrowth','Rent YoY'],['permitsChange','Permit YoY'],['multiShare','5+ unit share'],['rent','Monthly rent'],['units','Housing stock']].map(([k,l])=><th key={k} aria-sort={sort===k?(direction<0?'descending':'ascending'):'none'}><button onClick={()=>order(k)}>{l}{sort===k?(direction<0?' ↓':' ↑'):''}</button></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.code} data-selected={r.code===selected}><td><button onClick={()=>setSelected(r.code)}>{r.name}</button></td><td>{r.permitsPer1000?.toFixed(1)??'—'}</td><td style={{color:r.rentGrowth<0?'var(--chart-red)':undefined}}>{pct(r.rentGrowth)}</td><td>{pct(r.permitsChange)}</td><td>{r.multiShare==null?'—':`${r.multiShare.toFixed(0)}%`}</td><td>{r.rent==null?'—':`$${num(r.rent)}`}</td><td>{num(r.units)}</td></tr>)}</tbody></table></div></section>
    <details className="lab-panel"><summary>Sources, dates and interpretation</summary><p className="lab-note">New local-market sources: <a href={data.sources.households} target="_blank" rel="noreferrer">ACS household counts</a> and <a href={data.sources.householdsPrevious} target="_blank" rel="noreferrer">prior-year counts</a>; <a href={data.sources.income} target="_blank" rel="noreferrer">income by housing tenure</a>; <a href={data.sources.tenure} target="_blank" rel="noreferrer">renter/owner mix</a>. All use ACS 1-year estimates. The approximate margin on a household-count difference combines the two published 90% margins in quadrature, assuming independent estimates.</p><p className="lab-note">Monthly history: <a href={data.sources.rentHistory} target="_blank" rel="noreferrer">Zillow rent index</a> and <a href={data.sources.priceHistory} target="_blank" rel="noreferrer">home-value index</a>. A 3-month annualized rent pace compounds the latest 3-month change four times. {data.sources.permitsYtd&&<><a href={data.sources.permitsYtd} target="_blank" rel="noreferrer">Latest year-to-date permits</a> are compared with <a href={data.sources.permitsPreviousYtd} target="_blank" rel="noreferrer">the same months a year earlier</a>. </>}The monthly permit release is discovered from the Census release page when data refreshes.</p><p className="lab-note"><a href={data.sources.permits} target="_blank" rel="noreferrer">Census {data.permitYear} annual permits</a> and <a href={data.sources.previous} target="_blank" rel="noreferrer">prior-year permits</a> count authorized housing units, including single-family homes and condos. The 5+ category is not exclusively rental apartments. <a href={data.sources.stock} target="_blank" rel="noreferrer">ACS {data.stockYear} housing stock (B25001)</a> provides the denominator. These are fixed annual vintages, not current construction inventory.</p><p className="lab-note"><a href={data.sources.rents} target="_blank" rel="noreferrer">Zillow ZORI</a> tracks smoothed, seasonally adjusted asking rents across property types; it does not directly measure effective rent after concessions. Observation month: {data.rentDate}. Census data are joined by CBSA. Zillow uses the dashboard’s explicit metro-name mapping; historical boundary differences can remain. This comparison suggests questions to investigate; it does not establish that permits caused the rent change. Retrieved {data.fetchedAt.slice(0,10)}.</p><p className="lab-note">For {focus?.name}, ACS housing units: {num(focus?.units)}; published 90% margin of error: ±{num(focus?.stockMoe)}. Housing stock dates lag the permit flow. Permit intensity is a screening ratio, not a forecast of excess supply.</p></details>
  </>;
}
